POST http://localhost:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "email": "hassen@gmail.com",
    "username": "hassen",
    "password": "StrongPassword123",
    "re_password": "StrongPassword123",
    "first_name": "hassen",
    "last_name": "Mohsen",
    "phone_number": "0591234567",
    "birth_date": "1999-01-11"
}

###

POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "mohammed.basha.gg7845@gmail.com",
    "password": "123"
}

###

GET http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NjYxMzMzLCJpYXQiOjE3ODQ2NTc3MzQsImp0aSI6IjBlYzMwNTA1NDUwZDRlMTU5N2IxZGMzMGRmODI2NzBkIiwidXNlcl9pZCI6IjEifQ.JfY67G0UY58v27mlu-toR8zvKCQZURL1wL204BVdC8U

###

PATCH http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NjM1ODk1LCJpYXQiOjE3ODQ2MzIyOTUsImp0aSI6ImNiMGFjNTQ0ZjIwMTQwYTY5MGI0NmI0YmRmNzdkNGRlIiwidXNlcl9pZCI6IjIifQ.csfvLZMJ2lvMQtuJYh8wB5B7KFnMrQpsY-X6tdsl7aM
Content-Type: multipart/form-data

{
    "username": "N@O",
    "first_name": "Noor",
    "last_name": "Mohsen",
    "birth_date": "1991-12-21",
    "email": "noor@gmail.com"
}
