POST http://localhost:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "email": "hassen@gmail.com",
    "username": "hassen",
    "password": "StrongPassword123",
    "re_password": "StrongPassword123",
    "first_name": "hassen",
    "last_name": "Mohsen",
    "phone_number": "0591234567",
    "birth_date": "1999-01-11"
}

###

POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "noor@gmail.com",
    "password": "StrongPassword123"
}

###

GET http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NjMzODg3LCJpYXQiOjE3ODQ2MzAyODcsImp0aSI6IjcyYjAxYTQzZDFkODRlOWFhZGFjYjhlZDllOWFmODc2IiwidXNlcl9pZCI6IjQifQ.48XRTOXEsD9gE0mnV14EKnkPQwf_ofGB098fUCl8OWw

###

PATCH http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NjM1ODk1LCJpYXQiOjE3ODQ2MzIyOTUsImp0aSI6ImNiMGFjNTQ0ZjIwMTQwYTY5MGI0NmI0YmRmNzdkNGRlIiwidXNlcl9pZCI6IjIifQ.csfvLZMJ2lvMQtuJYh8wB5B7KFnMrQpsY-X6tdsl7aM
Content-Type: application/json

{
    "username": "N@O",
    "first_name": "Noor",
    "last_name": "Mohsen",
    "birth_date": "1991-12-21",
    "email": "noor@gmail.com"
}
