POST http://localhost:8000/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "email": "mohammed.basha.gg7845@gmail.com",
    "username": "noor",
    "password": "StrongPassword123",
    "re_password": "StrongPassword123",
    "first_name": "noor",
    "last_name": "mohsen",
    "birth_date": "1980-12-21"
}

###

POST http://localhost:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "mohammed.basha.gg7845@gmail.com",
    "password": "StrongPassword123"
}

###

GET http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0ODE0ODQ2LCJpYXQiOjE3ODQ4MTEyNDYsImp0aSI6ImQ3ZTNkZDM3Yjk3YzQyNjg5ZmUxOTRhNjJjZDg5YWRjIiwidXNlcl9pZCI6IjEifQ.ZiuYmygaQI236sqVTAqP7Eu8Ng9_iMWj3Nb4APITkRI

###

PATCH http://localhost:8000/auth/users/me/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NjM1ODk1LCJpYXQiOjE3ODQ2MzIyOTUsImp0aSI6ImNiMGFjNTQ0ZjIwMTQwYTY5MGI0NmI0YmRmNzdkNGRlIiwidXNlcl9pZCI6IjIifQ.csfvLZMJ2lvMQtuJYh8wB5B7KFnMrQpsY-X6tdsl7aM
Content-Type: multipart/form-data

{
    "username": "N@O",
    "first_name": "Noor",
    "last_name": "Mohsen",
    "birth_date": "1991-12-21",
    "email": "noor@gmail.com"
}

###

POST http://127.0.0.1:8000/auth/users/change-email/ HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0ODI3ODY1LCJpYXQiOjE3ODQ4MjQyNjUsImp0aSI6IjU5YmNiZTRjMWU5NjQ1YjhiNjhjNGNhNzQzMjFlZGFhIiwidXNlcl9pZCI6IjIifQ.YnDHZqVlX-BSIA9uOdrkME_hR8OSenuoaG0VFtEi9WA
Content-Type: application/json

{
    "email": "mohammed.basha.gg7845@gmail.com"
}

###

POST  http://127.0.0.1:8000/auth/users/confirm-email-change/ HTTP/1.1
Content-Type: application/json

{
    "uid":"Mg",
    "token":"dc6h6r-9dea72ec3fad696fb7655f677517356e"
}