# Generated by Django 6.0.7 on 2026-07-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveBigIntegerField(default=23),
            preserve_default=False,
        ),
    ]
