# Generated by Django 6.0.7 on 2026-07-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
